/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations, Outlines } from "@react-three/drei";
import { useGameStore } from "../../store/gameStore";

const ACTION_MAP = {
	death: "CharacterArmature|Death",
	gunShoot: "CharacterArmature|Gun_Shoot",
	hitReceive: "CharacterArmature|HitRecieve",
	hitReceive2: "CharacterArmature|HitRecieve_2",
	idle: "CharacterArmature|Idle",
	idleGun: "CharacterArmature|Idle_Gun",
	idleGunPointing: "CharacterArmature|Idle_Gun_Pointing",
	idleGunShoot: "CharacterArmature|Idle_Gun_Shoot",
	idleNeutral: "CharacterArmature|Idle_Neutral",
	idleSword: "CharacterArmature|Idle_Sword",
	interact: "CharacterArmature|Interact",
	kickLeft: "CharacterArmature|Kick_Left",
	kickRight: "CharacterArmature|Kick_Right",
	punchLeft: "CharacterArmature|Punch_Left",
	punchRight: "CharacterArmature|Punch_Right",
	roll: "CharacterArmature|Roll",
	run: "CharacterArmature|Run",
	runBack: "CharacterArmature|Run_Back",
	runLeft: "CharacterArmature|Run_Left",
	runRight: "CharacterArmature|Run_Right",
	runShoot: "CharacterArmature|Run_Shoot",
	swordSlash: "CharacterArmature|Sword_Slash",
	walk: "CharacterArmature|Walk",
	wave: "CharacterArmature|Wave",
};

export default function HoodedAdventurer(props) {
	const group = useRef();
	const [_, setHoveredCharacter] = useState(null);
	const npcId = "HoodedAdventurer";

	const { nodes, materials, animations } = useGLTF(
		"models/characters/testimonies/HoodedAdventurer.glb"
	);
	const { actions } = useAnimations(animations, group);

	const { interactWithNPC, getNPCAnimation, getNPCDialogStatus } =
		useGameStore();

	const currentAnimation = getNPCAnimation(npcId);
	const npcStatus = getNPCDialogStatus(npcId);

	const handlePointerOver = () => {
		setHoveredCharacter(npcId);

		document.body.style.cursor = "pointer";
	};

	const handlePointerOut = () => {
		setHoveredCharacter(null);
		document.body.style.cursor = "default";
	};

	const handleClick = (e) => {
		e.stopPropagation();
		if (npcStatus.canInteract) {
			interactWithNPC(npcId);
		}
	};

	useEffect(() => {
		if (!actions || Object.keys(actions).length === 0) return;
		const actionName = ACTION_MAP[currentAnimation];
		const targetAction = actions[actionName];

		if (targetAction) {
			Object.values(actions).forEach((action) => {
				if (action !== targetAction && action.isRunning()) {
					action.fadeOut(0.1);
				}
			});
			targetAction.reset().fadeIn(0.1).play();
		}
	}, [actions, npcId, currentAnimation]);

	useEffect(() => {
		if (actions && Object.keys(actions).length > 0) {
			const idleAction = actions[ACTION_MAP.idle];
			if (idleAction) {
				idleAction.play();
			}
		}
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={80}>
						<primitive object={nodes.Root} />
					</group>
					<group
						name='Medieval_Body'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
						onPointerOver={handlePointerOver}
						onPointerOut={handlePointerOut}
						onClick={handleClick}>
						<skinnedMesh
							name='Medieval_Body_1'
							geometry={nodes.Medieval_Body_1.geometry}
							material={materials.Black}
							skeleton={nodes.Medieval_Body_1.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Body_2'
							geometry={nodes.Medieval_Body_2.geometry}
							material={materials.LightBrown}
							skeleton={nodes.Medieval_Body_2.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Body_3'
							geometry={nodes.Medieval_Body_3.geometry}
							material={materials.DarkBrown}
							skeleton={nodes.Medieval_Body_3.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Body_4'
							geometry={nodes.Medieval_Body_4.geometry}
							material={materials.Skin}
							skeleton={nodes.Medieval_Body_4.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Body_5'
							geometry={nodes.Medieval_Body_5.geometry}
							material={materials.Gold}
							skeleton={nodes.Medieval_Body_5.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Body_6'
							geometry={nodes.Medieval_Body_6.geometry}
							material={materials.Metal}
							skeleton={nodes.Medieval_Body_6.skeleton}
						/>
					</group>
					<group
						name='Medieval_Feet'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<skinnedMesh
							name='Medieval_Feet_1'
							geometry={nodes.Medieval_Feet_1.geometry}
							material={materials.LightBrown}
							skeleton={nodes.Medieval_Feet_1.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Feet_2'
							geometry={nodes.Medieval_Feet_2.geometry}
							material={materials.DarkBrown}
							skeleton={nodes.Medieval_Feet_2.skeleton}
						/>
					</group>
					<group
						name='Medieval_Head'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
						onPointerOver={handlePointerOver}
						onPointerOut={handlePointerOut}
						onClick={handleClick}>
						<skinnedMesh
							name='Medieval_Head_1'
							geometry={nodes.Medieval_Head_1.geometry}
							material={materials.Black}
							skeleton={nodes.Medieval_Head_1.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Head_2'
							geometry={nodes.Medieval_Head_2.geometry}
							material={materials.DarkBrown}
							skeleton={nodes.Medieval_Head_2.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Head_3'
							geometry={nodes.Medieval_Head_3.geometry}
							material={materials.Skin}
							skeleton={nodes.Medieval_Head_3.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Head_4'
							geometry={nodes.Medieval_Head_4.geometry}
							material={materials.White}
							skeleton={nodes.Medieval_Head_4.skeleton}
						/>
						<skinnedMesh
							name='Medieval_Head_5'
							geometry={nodes.Medieval_Head_5.geometry}
							material={materials.Brown}
							skeleton={nodes.Medieval_Head_5.skeleton}
						/>
					</group>
					<skinnedMesh
						name='Medieval_Legs'
						geometry={nodes.Medieval_Legs.geometry}
						material={materials.Black}
						skeleton={nodes.Medieval_Legs.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
						onPointerOver={handlePointerOver}
						onPointerOut={handlePointerOut}
						onClick={handleClick}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/characters/testimonies/HoodedAdventurer.glb");
