/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Wizard(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"models/characters/testimonies/Wizard.glb"
	);
	const { actions } = useAnimations(animations, group);
	console.log("Wizard Actions: ", actions);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.Root} />
					</group>
					<skinnedMesh
						name='Wizard001'
						geometry={nodes.Wizard001.geometry}
						material={materials.Wizard_Texture}
						skeleton={nodes.Wizard001.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
					<group name='Wizard' rotation={[-Math.PI / 2, 0, 0]} scale={100} />
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/characters/testimonies/Wizard.glb");
