/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useControls } from "leva";

const ACTION_MAP = {
	death: "CharacterArmature|Death",
	duck: "CharacterArmature|Duck",
	hitReact: "CharacterArmature|HitReact",
	idle: "CharacterArmature|Idle",
	idleGun: "CharacterArmature|Idle_Gun",
	jump: "CharacterArmature|Jump",
	jumpIdle: "CharacterArmature|Jump_Idle",
	jumpLand: "CharacterArmature|Jump_Land",
	no: "CharacterArmature|No",
	punch: "CharacterArmature|Punch",
	run: "CharacterArmature|Run",
	runGun: "CharacterArmature|Run_Gun",
	runSlash: "CharacterArmature|Run_Slash",
	runStab: "CharacterArmature|Run_Stab",
	stab: "CharacterArmature|Stab",
	walk: "CharacterArmature|Walk",
	walkGun: "CharacterArmature|Walk_Gun",
	wave: "CharacterArmature|Wave",
	yes: "CharacterArmature|Yes",
};

export function Shaun(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"models/characters/Shaun.glb"
	);
	const { actions } = useAnimations(animations, group);
	console.log("Actions: ", actions);

	const { currentAnimation, animationSpeed } = useControls("Shaun Animation", {
		currentAnimation: {
			value: "idle",
			options: Object.keys(ACTION_MAP),
		},
		animationSpeed: { value: 1, min: 0.1, max: 3, step: 0.1 },
	});

	useEffect(() => {
		const actionName = ACTION_MAP[currentAnimation];
		if (actions[actionName]) {
			Object.values(actions).forEach((action) => action.stop());
			actions[actionName].reset().fadeIn(0.2).play();
			actions[actionName].timeScale = animationSpeed;
		}
	}, [currentAnimation, animationSpeed, actions]);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.Root} />
					</group>
					<skinnedMesh
						name='Shaun'
						geometry={nodes.Shaun.geometry}
						material={materials.Atlas}
						skeleton={nodes.Shaun.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/characters/Shaun.glb");
