/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, Outlines } from "@react-three/drei";
import { useState } from "react";
import { useGameStore } from "../store/gameStore";
import { DoorRound } from "./components/DoorRound";
import { Wall } from "./components/Wall";
import { folder, useControls } from "leva";
import { Window } from "./components/Window";
import { StaticCollider } from "bvhecctrl";

export default function Bedroom(bedroomClues, ...props) {
	console.log("Clues passed to bedroom: ", bedroomClues);

	const { nodes, materials } = useGLTF("models/rooms/bedroom.glb");
	// const [hovered, setHovered] = useState(false);
	const [hoveredObject, setHoveredObject] = useState(null);

	const { interactWithObject, getObjectStatus } = useGameStore();
	const hoverableClues = Object.keys(bedroomClues["clues"]);
	console.log("Hoverable clues: ", hoverableClues);

	const handlePointerOver = (objectId) => {
		console.log("Object id on Pointer Over: ", objectId);
		if (!hoverableClues.includes(objectId)) return;
		setHoveredObject(objectId);
		document.body.style.cursor = "pointer";
	};

	const handlePointerOut = () => {
		console.log("Hovering out");

		setHoveredObject(null);
		document.body.style.cursor = "grab";
	};

	const handleClick = (e, objectId) => {
		if (e && e.stopPropagation) {
			e.stopPropagation();
		}
		console.log("Clicked, id:", objectId);
		interactWithObject(objectId);
	};

	const getOutlineColor = (objectId) => {
		const status = getObjectStatus(objectId);
		if (status.isFound) return "#90ee90";
		if (status.isClue) return "#ffd700";
		return "aquamarine";
	};

	const { changeRoom } = useGameStore();
	const [hoveredDoor, setHoveredDoor] = useState(null);

	const handleDoorClick = (roomName) => {
		console.log(`Clicked door to ${roomName}`);
		changeRoom(roomName);
	};

	const handleDoorHover = (doorName) => {
		setHoveredDoor(doorName);
		console.log(`Hovered over: ${hoveredDoor}`);
		document.body.style.cursor = "pointer";
	};

	const handleDoorHoverOut = () => {
		setHoveredDoor(null);
		document.body.style.cursor = "grab";
	};

	const {
		bWall1Px,
		bWall1Py,
		bWall1Pz,
		bWall1Rx,
		bWall1Ry,
		bWall1Rz,
		bWall2Px,
		bWall2Py,
		bWall2Pz,
		bWall2Rx,
		bWall2Ry,
		bWall2Rz,
		bWall3Px,
		bWall3Py,
		bWall3Pz,
		bWall3Rx,
		bWall3Ry,
		bWall3Rz,
		bWall4Px,
		bWall4Py,
		bWall4Pz,
		bWall4Rx,
		bWall4Ry,
		bWall4Rz,
		bWall5Px,
		bWall5Py,
		bWall5Pz,
		bWall5Rx,
		bWall5Ry,
		bWall5Rz,
		bWall6Px,
		bWall6Py,
		bWall6Pz,
		bWall6Rx,
		bWall6Ry,
		bWall6Rz,
		bWin1Px,
		bWin1Py,
		bWin1Pz,
		bWin1Rx,
		bWin1Ry,
		bWin1Rz,
		bWin2Px,
		bWin2Py,
		bWin2Pz,
		bWin2Rx,
		bWin2Ry,
		bWin2Rz,
		bWin3Px,
		bWin3Py,
		bWin3Pz,
		bWin3Rx,
		bWin3Ry,
		bWin3Rz,
	} = useControls({
		BWalls: folder(
			{
				// wall 1 Position
				bWall1Px: { value: 1.65, min: -10, max: 10, step: 0.01 },
				bWall1Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall1Pz: { value: -3.2, min: -10, max: 10, step: 0.01 },
				// bWall 1 Rotation
				bWall1Rx: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall1Ry: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall1Rz: { value: 0, min: -3, max: 3, step: 0.01 },
				// bWall 2 Position
				bWall2Px: { value: -5.6, min: -10, max: 10, step: 0.01 },
				bWall2Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall2Pz: { value: -1.9, min: -10, max: 10, step: 0.01 },
				// bWall 2 Rotation
				bWall2Rx: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall2Ry: { value: 0.69, min: -3, max: 3, step: 0.01 },
				bWall2Rz: { value: 0, min: -3, max: 3, step: 0.01 },
				// bWall 3 Position
				bWall3Px: { value: 8, min: -10, max: 10, step: 0.01 },
				bWall3Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall3Pz: { value: -1.6, min: -10, max: 10, step: 0.01 },
				// bWall 3 Rotation
				bWall3Rx: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall3Ry: { value: Math.PI * 0.5, min: -3, max: 3, step: 0.01 },
				bWall3Rz: { value: 0, min: -3, max: 3, step: 0.01 },
				// bWall 4 Position
				bWall4Px: { value: 8, min: -10, max: 10, step: 0.01 },
				bWall4Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall4Pz: { value: 2.33, min: -10, max: 10, step: 0.01 },
				// bWall 4 Rotation
				bWall4Rx: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall4Ry: { value: Math.PI * 0.5, min: -3, max: 3, step: 0.01 },
				bWall4Rz: { value: 0, min: -3, max: 3, step: 0.01 },
				// bWall 5 Position
				bWall5Px: { value: 5.56, min: -10, max: 10, step: 0.01 },
				bWall5Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall5Pz: { value: -3.2, min: -10, max: 10, step: 0.01 },
				// bWall 5 Rotation
				bWall5Rx: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall5Ry: { value: 0, min: -3, max: 3, step: 0.01 },
				bWall5Rz: { value: 0, min: -3, max: 3, step: 0.01 },
				// bWall 6 Position
				bWall6Px: { value: -6.8, min: -20, max: 20, step: 0.01 },
				bWall6Py: { value: 0, min: -20, max: 20, step: 0.01 },
				bWall6Pz: { value: 4.8, min: -20, max: 20, step: 0.01 },
				// bWall 6 Rotation
				bWall6Rx: { value: 0, min: -10, max: 10, step: 0.01 },
				bWall6Ry: { value: 1.57, min: -10, max: 10, step: 0.01 },
				bWall6Rz: { value: 0, min: -10, max: 10, step: 0.01 },
			},
			{ collapsed: true }
		),
		Windows: folder(
			{
				bWin1Px: { value: -2.2, min: -10, max: 10, step: 0.01 },
				bWin1Py: { value: 0, min: -10, max: 10, step: 0.01 },
				bWin1Pz: { value: -3.1, min: -10, max: 10, step: 0.01 },
				// bWin 1 rotation
				bWin1Rx: { value: 0, min: -10, max: 10, step: 0.01 },
				bWin1Ry: { value: 0, min: -10, max: 10, step: 0.01 },
				bWin1Rz: { value: 0, min: -10, max: 10, step: 0.01 },
				// bWin 2 position
				bWin2Px: { value: -6.8, min: -20, max: 20, step: 0.01 },
				bWin2Py: { value: 0, min: -20, max: 20, step: 0.01 },
				bWin2Pz: { value: 0.89, min: -20, max: 20, step: 0.01 },
				// bWin 2 rotation
				bWin2Rx: { value: 0, min: -10, max: 10, step: 0.01 },
				bWin2Ry: { value: 1.57, min: -10, max: 10, step: 0.01 },
				bWin2Rz: { value: 0, min: -10, max: 10, step: 0.01 },
				// bWin 3 position
				bWin3Px: { value: 7.58, min: -20, max: 20, step: 0.01 },
				bWin3Py: { value: 0, min: -20, max: 20, step: 0.01 },
				bWin3Pz: { value: 6.24, min: -20, max: 20, step: 0.01 },
				// bWin 3 rotation
				bWin3Rx: { value: 0, min: -10, max: 10, step: 0.01 },
				bWin3Ry: { value: -1.55, min: -10, max: 10, step: 0.01 },
				bWin3Rz: { value: 0, min: -10, max: 10, step: 0.01 },
			},
			{ collapsed: true }
		),
	});

	return (
		<>
			<DoorRound
				position={[7.1, 0, 1.3]}
				scale={3}
				rotation={[0, -Math.PI * 0.5, 0]}
				onPointerOver={() => handleDoorHover("hall")}
				onPointerOut={() => handleDoorHoverOut()}
				onClick={() => handleDoorClick("hall")}
				isHovered={hoveredDoor === "hall"}
			/>
			<Wall
				position={[bWall1Px, bWall1Py, bWall1Pz]}
				rotation={[bWall1Rx, bWall1Ry, bWall1Rz]}
				scale={2}
			/>
			<Wall
				position={[bWall2Px, bWall2Py, bWall2Pz]}
				scale={2}
				rotation={[bWall2Rx, bWall2Ry, bWall2Rz]}
			/>
			<Wall
				position={[bWall3Px, bWall3Py, bWall3Pz]}
				rotation={[bWall3Rx, bWall3Ry, bWall3Rz]}
				scale={2}
			/>
			<Wall
				position={[bWall4Px, bWall4Py, bWall4Pz]}
				rotation={[bWall4Rx, bWall4Ry, bWall4Rz]}
				scale={2}
			/>
			<Window
				scale={2}
				position={[bWin1Px, bWin1Py, bWin1Pz]}
				rotation={[bWin1Rx, bWin1Ry, bWin1Rz]}
			/>
			<Window
				position={[bWin2Px, bWin2Py, bWin2Pz]}
				rotation={[bWin2Rx, bWin2Ry, bWin2Rz]}
				scale={2}
			/>
			<Window
				position={[bWin3Px, bWin3Py, bWin3Pz]}
				rotation={[bWin3Rx, bWin3Ry, bWin3Rz]}
				scale={2}
			/>
			<Wall
				position={[bWall5Px, bWall5Py, bWall5Pz]}
				rotation={[bWall5Rx, bWall5Ry, bWall5Rz]}
				scale={2}
			/>
			<Wall
				position={[bWall6Px, bWall6Py, bWall6Pz]}
				rotation={[bWall6Rx, bWall6Ry, bWall6Rz]}
				scale={2}
			/>
			<StaticCollider>
				<mesh position={[0, 1, 6.7]} visible={false}>
					<boxGeometry args={[16, 5, 0.2]} />
					<meshBasicMaterial transparent opacity={0} />
				</mesh>
			</StaticCollider>

			<group {...props} dispose={null}>
				{/* Bed 1 with blue duvet */}
				<group
					position={[2.981, 0, -1.254]}
					onPointerOver={() => handlePointerOver("bed1")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "bed1")}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube001.geometry}
						material={materials["MI_Trim_Furniture.010"]}>
						{hoveredObject === "bed1" && hoverableClues.includes("bed1") && (
							<Outlines thickness={0.6} color={getOutlineColor("bed1")} />
						)}
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube001_1.geometry}
						material={materials["MI_Trim_Metal.012"]}>
						{hoveredObject === "bed1" && hoverableClues.includes("bed1") && (
							<Outlines thickness={0.6} color={getOutlineColor("bed1")} />
						)}
					</mesh>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube001_2.geometry}
						material={materials["MI_Trim_Cloth.003"]}
						// onPointerOver={() => handlePointerOver("bed1")}
						// onPointerOut={() => handlePointerOut()}
						// onClick={(e) => handleClick(e, "bed1")}
					>
						{hoveredObject === "bed1" && hoverableClues.includes("bed1") && (
							<Outlines thickness={2.0} color='aquamarine' />
						)}
					</mesh>
				</group>
				{/* Bed2 on the left*/}
				<group position={[-2.556, 0, -1.23]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube002.geometry}
						material={materials["MI_Trim_Furniture.011"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube002_1.geometry}
						material={materials["MI_Trim_Metal.013"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube002_2.geometry}
						material={materials["MI_Trim_Cloth.004"]}
					/>
				</group>
				{/* Book 5 on the right bookshelf, second shelf from the top, solo book at an angle*/}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Book_5.geometry}
					material={materials["MI_Trim_Props_Vertex.002"]}
					position={[0.726, 1.571, -2.721]}
					rotation={[0, -1.176, 0]}
				/>
				{/* Something */}
				<group position={[0.021, 0.614, -1.71]} rotation={[0, 0.628, 0]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube133.geometry}
						material={materials["MI_Trim_Props_Vertex.003"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube133_1.geometry}
						material={materials["MI_Trim_Metal.015"]}
					/>
				</group>
				<group position={[-4.071, 1.004, -2.257]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube151.geometry}
						material={materials["MI_Trim_Props_Vertex.006"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube151_1.geometry}
						material={materials["MI_Trim_Metal.016"]}
					/>
				</group>
				{/* Books top shelf of left bookshelf */}
				<group position={[-0.907, 0, -2.796]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube168.geometry}
						material={materials["MI_Trim_Furniture.013"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube168_1.geometry}
						material={materials["MI_Trim_Metal.017"]}
					/>
				</group>
				{/* Books on the right side of the bottom shelf of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_1.geometry}
					material={materials["MI_Trim_Props_Vertex.010"]}
					position={[-0.693, 0.764, -2.763]}
				/>
				{/* Bottle top right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bottle_1.geometry}
					material={materials["MI_Trim_Props_Vertex.013"]}
					position={[1.259, 1.92, -2.781]}
					scale={0.621}
					onPointerOver={() => handlePointerOver("bottle")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "bottle")}>
					{hoveredObject === "bottle" && hoverableClues.includes("bottle") && (
						<Outlines thickness={0.6} color={getOutlineColor("bottle")} />
					)}
				</mesh>
				{/* Bucket  */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Bucket_Metal.geometry}
					material={materials["MI_Trim_Metal.018"]}
					position={[5.396, 0, -0.341]}
					onPointerOver={() => handlePointerOver("bucket")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "bucket")}>
					{hoveredObject === "bucket" && (
						<Outlines thickness={0.6} color={getOutlineColor("bucket")} />
					)}
				</mesh>
				{/* Dresser next to the right bed */}
				<group position={[4.826, 0, -2.271]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube098.geometry}
						material={materials["MI_Trim_Furniture.016"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube098_1.geometry}
						material={materials["MI_Trim_Metal.020"]}
					/>
				</group>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cage_Small.geometry}
					material={materials["MI_Trim_Metal.021"]}
					position={[-2.518, 0, 0.936]}
					rotation={[0, 1.482, 0]}
					onPointerOver={() => handlePointerOver("cage")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "cage")}>
					{hoveredObject === "cage" && hoverableClues.includes("cage") && (
						<Outlines thickness={0.6} color={getOutlineColor("cage")} />
					)}
				</mesh>
				{/* Candle on left bookshelf second shelf from the top */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Candle_1.geometry}
					material={materials["MI_Trim_Props.001"]}
					position={[-0.608, 1.542, -2.77]}
				/>
				{/* Candle on left bookshelf bottom shelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Candle_2.geometry}
					material={materials["MI_Trim_Props.002"]}
					position={[-1.181, 0.761, -2.751]}
					scale={0.817}
				/>
				{/* Empty candle stick left bookshelf top shelf on the left */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.CandleStick.geometry}
					material={materials["MI_Trim_Metal.022"]}
					position={[-1.239, 1.914, -2.78]}
				/>
				{/* Big group of candle lamps on the right */}
				<group position={[4.25, 0, 1.214]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder127.geometry}
						material={materials["MI_Trim_Metal.023"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder127_1.geometry}
						material={materials["MI_Trim_Props_Vertex.014"]}
					/>
				</group>

				{/* Candle Stick on dresser by the right bed with blue blanket */}
				<group
					position={[4.419, 1, -2.266]}
					rotation={[0, 0.353, 0]}
					scale={1.5}>
					{hoveredObject === "candlestick" &&
						hoverableClues.includes("candlestick") && (
							<Outlines
								thickness={0.8}
								color={getOutlineColor("candlestick")}
							/>
						)}
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder091.geometry}
						material={materials["MI_Trim_Metal.024"]}
						onPointerOver={() => handlePointerOver("candlestick")}
						onPointerOut={() => handlePointerOut()}
						onClick={(e) => handleClick(e, "candlestick")}>
						{hoveredObject === "candlestick" &&
							hoverableClues.includes("candlestick") && (
								<Outlines
									thickness={0.8}
									color={getOutlineColor("candlestick")}
								/>
							)}
					</mesh>
					<mesh
						onPointerOver={() => handlePointerOver("candlestick")}
						onPointerOut={() => handlePointerOut()}
						onClick={(e) => handleClick(e, "candlestick")}
						castShadow
						receiveShadow
						geometry={nodes.Cylinder091_1.geometry}
						material={materials["MI_Trim_Props.003"]}>
						{hoveredObject === "candlestick" &&
							hoverableClues.includes("candlestick") && (
								<Outlines
									thickness={0.8}
									color={getOutlineColor("candlestick")}
								/>
							)}
					</mesh>
				</group>

				{/* Chalice by the left bed on the dresser  */}
				<mesh
					castShadow
					receiveShadow
					scale={1.5}
					geometry={nodes.Chalice.geometry}
					material={materials["MI_Trim_Metal.028"]}
					position={[-4.35, 1.004, -2.286]}
					onPointerOver={() => handlePointerOver("chalice")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "chalice")}>
					{hoveredObject === "chalice" &&
						hoverableClues.includes("chalice") && (
							<Outlines thickness={0.9} color={getOutlineColor("chalice")} />
						)}
				</mesh>

				{/* Ceiling Chandelier */}
				<group position={[0.13, 4.241, -0.682]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder092.geometry}
						material={materials["MI_Trim_Metal.029"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder092_1.geometry}
						material={materials["MI_Trim_Furniture.018"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder092_2.geometry}
						material={materials["MI_Trim_Props_Vertex.016"]}
					/>
				</group>

				{/* Top shelf middle coin pile right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Coin_Pile.geometry}
					material={materials["MI_Trim_Metal_Vertex.001"]}
					position={[0.842, 1.917, -2.809]}
				/>

				{/* Coin pile dresser by the right bed */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Coin_Pile_2.geometry}
					material={materials["MI_Trim_Metal_Vertex.002"]}
					position={[-4.684, 1.004, -2.239]}
				/>

				{/* Weapon Pell near right bed */}
				<group
					position={[-5.685, 0, -0.954]}
					rotation={[0, 0.754, 0]}
					onPointerOver={() => handlePointerOver("figure")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "figure")}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube223.geometry}
						material={materials["MI_Trim_Furniture.022"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube223_1.geometry}
						material={materials["MI_Trim_Metal.033"]}
					/>

					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube223_2.geometry}
						material={materials["MI_Trim_Cloth.005"]}>
						{hoveredObject === "figure" &&
							hoverableClues.includes("figure") && (
								<Outlines thickness={0.8} color='green' />
							)}
					</mesh>
				</group>

				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Stool.geometry}
					material={materials["MI_Trim_Furniture.023"]}
					position={[-0.001, 0, -1.701]}
					onPointerOver={() => handlePointerOver("Dairy")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "Dairy")}>
					{hoveredObject === "Dairy" && (
						<Outlines thickness={0.6} color={getOutlineColor("Dairy")} />
					)}
				</mesh>

				{/* 	Right bookshelf */}
				<group position={[0.972, 0, -2.796]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube005.geometry}
						material={materials["MI_Trim_Furniture.013"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube005_1.geometry}
						material={materials["MI_Trim_Metal.017"]}
					/>
				</group>

				{/* Candle stick lamp group on the left */}
				<group position={[-3.861, 0, 2.058]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001.geometry}
						material={materials["MI_Trim_Metal.023"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cylinder001_1.geometry}
						material={materials["MI_Trim_Props_Vertex.014"]}
					/>
				</group>

				{/* Dresser drawer by the right hand side bed */}
				<group position={[-4.492, 0, -2.239]}>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube007.geometry}
						material={materials["MI_Trim_Furniture.016"]}
					/>
					<mesh
						castShadow
						receiveShadow
						geometry={nodes.Cube007_1.geometry}
						material={materials["MI_Trim_Metal.020"]}
					/>
				</group>

				{/* Book group on the right of the bottom shelf of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2001.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[-0.468, 0.774, -2.736]}
				/>

				{/* Group of books to the right of the second shelf from the bottom of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2002.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[-0.676, 1.276, -2.736]}
					rotation={[0, -0.1, -1.587]}
				/>

				{/* Group of books to the left of the second shelf from the bottom of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2003.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[-1.36, 1.158, -2.736]}
				/>

				{/* Group of books to the left of the second shelf from the top of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2004.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[-1.081, 1.546, -2.736]}
				/>

				{/* Group of books to the top of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2005.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[-0.914, 1.924, -2.736]}
				/>

				{/* Empty Candle Stick on bottom shelf of bookshelf of right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.CandleStick001.geometry}
					material={materials["MI_Trim_Metal.022"]}
					position={[1.185, 0.772, -2.78]}
				/>

				{/* Group of books to the right second shelf from the top of the right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2006.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[1.075, 1.53, -2.736]}
				/>

				{/* Group of books to the left bottom shelf of the right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_2008.geometry}
					material={materials["MI_Trim_Props_Vertex.011"]}
					position={[0.537, 0.775, -2.736]}
				/>

				{/* Group of books to the left of the second shelf from the top of the left bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_1001.geometry}
					material={materials["MI_Trim_Props_Vertex.010"]}
					position={[-1.312, 1.549, -2.763]}
				/>

				{/* Books on second shelf to the right of the right bookshelf */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookGroup_Small_1002.geometry}
					material={materials["MI_Trim_Props_Vertex.010"]}
					position={[1.19, 1.158, -2.763]}
					onPointerOver={() => handlePointerOver("books")}
					onPointerOut={() => handlePointerOut()}
					onClick={(e) => handleClick(e, "books")}>
					{hoveredObject === "books" && (
						<Outlines thickness={0.6} color={getOutlineColor("books")} />
					)}
				</mesh>

				{/* Small pile of coins on the left most side of the top book shelf on the right  */}
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Coin_Pile001.geometry}
					material={materials["MI_Trim_Metal_Vertex.001"]}
					position={[0.603, 1.917, -2.809]}
					rotation={[0, -0.417, 0]}
					scale={0.698}
					onPointerEnter={() => (document.body.style.cursor = "pointer")}
					onPointerLeave={() => (document.body.style.cursor = "grab")}
					onClick={() => {
						console.log("*** YES! Book group clicked ");
					}}
				/>
			</group>
		</>
	);
}

useGLTF.preload("models/rooms/bedroom.glb");
