/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Library(props) {
	const { nodes, materials } = useGLTF("models/library.glb");
	return (
		<group {...props} dispose={null}>
			<group position={[-4.96, 0, -6.506]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder036.geometry}
					material={materials.MI_Trim_Furniture}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder036_1.geometry}
					material={materials["MI_Trim_Metal.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder036_2.geometry}
					material={materials.MI_Trim_Props}
				/>
			</group>
			<group position={[0.052, 2.495, -6.616]} scale={0.735}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube227.geometry}
					material={materials["MI_Trim_Metal.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube227_1.geometry}
					material={materials["MI_Banner.001"]}
				/>
			</group>
			<group position={[-2.345, -0.019, -1.774]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube011.geometry}
					material={materials["MI_Trim_Furniture.009"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube011_1.geometry}
					material={materials["MI_Trim_Metal.011"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_5.geometry}
				material={materials["MI_Trim_Props_Vertex.002"]}
				position={[-2.929, 0.896, -2.77]}
				rotation={[0, 0.691, 0]}
			/>
			<group position={[-8.74, 1.333, -4.827]} rotation={[1.05, 0.48, -0.772]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube133.geometry}
					material={materials["MI_Trim_Props_Vertex.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube133_1.geometry}
					material={materials["MI_Trim_Metal.012"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_Simplified_Single.geometry}
				material={materials["MI_Trim_Props_Vertex.004"]}
				position={[-7.046, 1.155, -6.644]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_Stack_1.geometry}
				material={materials["MI_Trim_Props_Vertex.005"]}
				position={[-6.24, 0.764, -6.613]}
			/>
			<group
				position={[-2.302, 0.765, -6.547]}
				rotation={[0, 0.196, 0]}
				scale={0.757}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube151.geometry}
					material={materials["MI_Trim_Props_Vertex.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube151_1.geometry}
					material={materials["MI_Trim_Metal.013"]}
				/>
			</group>
			<group position={[-3.299, 0, -6.609]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube168.geometry}
					material={materials["MI_Trim_Furniture.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube168_1.geometry}
					material={materials["MI_Trim_Metal.014"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_1.geometry}
				material={materials["MI_Trim_Props_Vertex.007"]}
				position={[-3.342, 1.148, -6.535]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_2.geometry}
				material={materials["MI_Trim_Props_Vertex.008"]}
				position={[-8.045, 1.096, -6.566]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_3.geometry}
				material={materials["MI_Trim_Props_Vertex.009"]}
				position={[-3.248, 0.765, -6.581]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_1.geometry}
				material={materials["MI_Trim_Props_Vertex.010"]}
				position={[-6.905, 1.529, -6.584]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_2.geometry}
				material={materials["MI_Trim_Props_Vertex.011"]}
				position={[-6.612, 1.918, -6.615]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_3.geometry}
				material={materials["MI_Trim_Props_Vertex.012"]}
				position={[-6.538, 0.767, -6.548]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookStand.geometry}
				material={materials["MI_Trim_Furniture.011"]}
				position={[-8.741, 0, -4.82]}
				rotation={[0, 0.858, 0]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bottle_1.geometry}
				material={materials["MI_Trim_Props_Vertex.013"]}
				position={[1.636, 1.523, -6.575]}
				scale={0.658}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Bucket_Metal.geometry}
				material={materials["MI_Trim_Metal.015"]}
				position={[-5.584, 0, -1.955]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.CandleStick.geometry}
				material={materials["MI_Trim_Metal.019"]}
				position={[1.585, 0.809, -2.394]}
			/>
			<group position={[3.534, 0, -6.442]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder127.geometry}
					material={materials["MI_Trim_Metal.020"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder127_1.geometry}
					material={materials["MI_Trim_Props_Vertex.014"]}
				/>
			</group>
			<group position={[3.492, 0.794, -3.476]} rotation={[0, -0.995, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder091.geometry}
					material={materials["MI_Trim_Metal.021"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder091_1.geometry}
					material={materials["MI_Trim_Props.003"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Chain_Coil.geometry}
				material={materials["MI_Trim_Metal.023"]}
				position={[-7.05, 0.81, -3.716]}
			/>
			<group position={[2.183, 0, -3.811]} rotation={[0, 0.481, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube180.geometry}
					material={materials["MI_Trim_Furniture.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube180_1.geometry}
					material={materials["MI_Trim_Metal.024"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Coin_Pile.geometry}
				material={materials["MI_Trim_Metal_Vertex.001"]}
				position={[-6.151, 0.831, -2.812]}
				rotation={[0, 0.444, 0]}
			/>
			<group position={[-7.222, -0.02, -1.778]} scale={0.784}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube035.geometry}
					material={materials["MI_Trim_Furniture.017"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube035_1.geometry}
					material={materials["MI_Trim_Metal.028"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Key_Gold.geometry}
				material={materials["MI_Trim_Metal_Vertex.003"]}
				position={[2.921, 0.354, -3.445]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Key_Metal.geometry}
				material={materials["MI_Trim_Metal.034"]}
				position={[-6.567, 0.81, -2.822]}
				scale={1.513}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Lantern_Wall.geometry}
				material={materials["MI_Trim_Metal.035"]}
				position={[4.332, 1.607, -6.716]}
			/>
			<group position={[2.329, 1.538, -6.574]} scale={1.287}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder068.geometry}
					material={materials["MI_Trim_Metal.036"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder068_1.geometry}
					material={materials["MI_Trim_Furniture.023"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Potion_2.geometry}
				material={materials["MI_Trim_Props_Vertex.021"]}
				position={[2.364, 0.758, -6.613]}
				scale={0.804}
			/>
			<group position={[-5.861, 0.819, -2.677]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube152.geometry}
					material={materials.MI_Page_Empty}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube152_1.geometry}
					material={materials["MI_Trim_Props_Vertex.024"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf_Simple.geometry}
				material={materials["MI_Trim_Furniture.030"]}
				position={[-8.041, 0.417, -6.793]}
			/>
			<group position={[0.076, 0, -6.759]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube166.geometry}
					material={materials["MI_Trim_Props_Vertex.026"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube166_1.geometry}
					material={materials["MI_Trim_Metal.042"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube166_2.geometry}
					material={materials["MI_Trim_Furniture.031"]}
				/>
			</group>
			<group position={[-4.964, 1.85, -6.564]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube193.geometry}
					material={materials["MI_Trim_Furniture.032"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube193_1.geometry}
					material={materials["MI_Trim_Metal_Vertex.004"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube193_2.geometry}
					material={materials["MI_Trim_Props.004"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sword_Bronze.geometry}
				material={materials["MI_Trim_Props_Vertex.029"]}
				position={[-2.046, 0.902, -2.921]}
				rotation={[1.533, -0.014, 1.7]}
			/>
			<group position={[2.469, 0, -2.862]} rotation={[0, 0.521, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube084.geometry}
					material={materials["MI_Trim_Furniture.036"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube084_1.geometry}
					material={materials["MI_Trim_Metal.047"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Table_Plate.geometry}
				material={materials["MI_Trim_Metal.048"]}
				position={[-6.148, 0.82, -2.806]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Vase_2.geometry}
				material={materials["MI_Trim_Props_Vertex.030"]}
				position={[2.586, 0.823, -2.918]}
			/>
			<group position={[-2.445, -0.017, -2.945]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube163.geometry}
					material={materials["MI_Trim_Furniture.039"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube163_1.geometry}
					material={materials["MI_Trim_Metal.053"]}
				/>
			</group>
			<group position={[-1.848, 0, -6.609]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003.geometry}
					material={materials["MI_Trim_Furniture.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube003_1.geometry}
					material={materials["MI_Trim_Metal.014"]}
				/>
			</group>
			<group position={[2.072, 0, -6.609]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube004.geometry}
					material={materials["MI_Trim_Furniture.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube004_1.geometry}
					material={materials["MI_Trim_Metal.014"]}
				/>
			</group>
			<group position={[-6.531, 0, -6.609]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube005.geometry}
					material={materials["MI_Trim_Furniture.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube005_1.geometry}
					material={materials["MI_Trim_Metal.014"]}
				/>
			</group>
			<group position={[-2.345, 0, -4.055]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube006.geometry}
					material={materials["MI_Trim_Furniture.009"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube006_1.geometry}
					material={materials["MI_Trim_Metal.011"]}
				/>
			</group>
			<group position={[-6.655, 0, -3.259]} rotation={[0, -0.749, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube007.geometry}
					material={materials["MI_Trim_Furniture.036"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube007_1.geometry}
					material={materials["MI_Trim_Metal.047"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Lantern_Wall001.geometry}
				material={materials["MI_Trim_Metal.035"]}
				position={[-7.904, 1.607, -6.716]}
			/>
			<group
				position={[3.506, 0, -2.302]}
				rotation={[Math.PI, -0.497, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube009.geometry}
					material={materials["MI_Trim_Furniture.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube009_1.geometry}
					material={materials["MI_Trim_Metal.024"]}
				/>
			</group>
			<group
				position={[2.419, 0, -1.726]}
				rotation={[Math.PI, -0.497, Math.PI]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012.geometry}
					material={materials["MI_Trim_Furniture.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube012_1.geometry}
					material={materials["MI_Trim_Metal.024"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf_Simple001.geometry}
				material={materials["MI_Trim_Furniture.030"]}
				position={[-8.041, 0.987, -6.793]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_3001.geometry}
				material={materials["MI_Trim_Props_Vertex.009"]}
				position={[-1.918, 1.536, -6.581]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_1001.geometry}
				material={materials["MI_Trim_Props_Vertex.007"]}
				position={[-1.702, 0.767, -6.535]}
				scale={0.853}
			/>
			<group position={[-3.32, 1.916, -6.537]} rotation={[0, -0.144, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube020.geometry}
					material={materials["MI_Trim_Props_Vertex.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube020_1.geometry}
					material={materials["MI_Trim_Metal.013"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_1001.geometry}
				material={materials["MI_Trim_Props_Vertex.010"]}
				position={[1.654, 0.789, -6.584]}
				scale={0.868}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Potion_2001.geometry}
				material={materials["MI_Trim_Props_Vertex.021"]}
				position={[-6.093, 1.215, -6.612]}
				rotation={[0, 0, 1.774]}
				scale={0.822}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Potion_2002.geometry}
				material={materials["MI_Trim_Props_Vertex.021"]}
				position={[1.754, 1.529, -6.613]}
				scale={0.747}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Medium_3002.geometry}
				material={materials["MI_Trim_Props_Vertex.009"]}
				position={[2.165, 1.133, -6.581]}
			/>
			<group position={[-6.267, 1.533, -6.537]} rotation={[0, -0.533, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001.geometry}
					material={materials["MI_Trim_Props_Vertex.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cube001_1.geometry}
					material={materials["MI_Trim_Metal.013"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_3001.geometry}
				material={materials["MI_Trim_Props_Vertex.012"]}
				position={[-7.007, 0.767, -6.548]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.BookGroup_Small_3002.geometry}
				material={materials["MI_Trim_Props_Vertex.012"]}
				position={[-6.679, 1.54, -6.548]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Potion_2003.geometry}
				material={materials["MI_Trim_Props_Vertex.021"]}
				position={[-6.947, 1.154, -6.613]}
				scale={0.627}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Potion_2004.geometry}
				material={materials["MI_Trim_Props_Vertex.021"]}
				position={[-6.84, 1.154, -6.613]}
				scale={0.944}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Book_Simplified_Single001.geometry}
				material={materials["MI_Trim_Props_Vertex.004"]}
				position={[-5.993, 1.155, -6.644]}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Vase_2001.geometry}
				material={materials["MI_Trim_Props_Vertex.030"]}
				position={[2.062, 1.923, -6.59]}
				scale={0.352}
			/>
		</group>
	);
}

useGLTF.preload("models/library.glb");
