/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function ArchDoor(props) {
	const { nodes, materials } = useGLTF("models/components/ArchDoor.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Arch_Door_bottompivot_1.geometry}
					material={materials.DarkWood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Arch_Door_bottompivot_2.geometry}
					material={materials.Metal}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Arch_Door_bottompivot_3.geometry}
					material={materials.DarkMetal}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Arch_Door_bottompivot_4.geometry}
					material={materials.Wood}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/components/ArchDoor.glb");
