/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function DoorRound(props) {
	const { nodes, materials } = useGLTF("models/components/DoorRound.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Door_Round_1.geometry}
					material={materials.Stone_Dark}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Door_Round_2.geometry}
					material={materials.Wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Door_Round_3.geometry}
					material={materials.Wood_Light}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Door_Round_4.geometry}
					material={materials.Stone_Light}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/components/DoorRound.glb");
