/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function WallTower(props) {
	const { nodes, materials } = useGLTF("models/components/WallTower.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WallTowers_Door_SecondAge_1.geometry}
					material={materials.Stone_Light}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WallTowers_Door_SecondAge_2.geometry}
					material={materials.Stone}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WallTowers_Door_SecondAge_3.geometry}
					material={materials.Wood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.WallTowers_Door_SecondAge_4.geometry}
					material={materials.Main}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/components/WallTower.glb");
