/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Wall(props) {
	const { nodes, materials } = useGLTF("models/components/Wall.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Wall_1.geometry}
					material={materials.Highlights}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Wall_2.geometry}
					material={materials.Main}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/components/Wall.glb");
