/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function Window(props) {
	const { nodes, materials } = useGLTF("models/components/WindowBars.glb");
	return (
		<group {...props} dispose={null}>
			<group rotation={[Math.PI, 0, 0]} scale={[100, 100, 5.973]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Window_Bars_1.geometry}
					material={materials.Highlights}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Window_Bars_2.geometry}
					material={materials.Main}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Window_Bars_3.geometry}
					material={materials.Metal}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/components/WindowBars.glb");
