/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function AstroFrog(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"models/characters/AstroFrog.glb"
	);
	const { actions } = useAnimations(animations, group);

	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={60}>
						<primitive object={nodes.Root} />
					</group>
					<skinnedMesh
						name='FinnTheFrog'
						geometry={nodes.FinnTheFrog.geometry}
						material={materials.Atlas}
						skeleton={nodes.FinnTheFrog.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/characters/AstroFrog.glb");
