/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Fish(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF(
		"models/characters/Fish.glb"
	);
	const { actions } = useAnimations(animations, group);
	console.log("Fish Actions: ", actions);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='CharacterArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={50}>
						<primitive object={nodes.Root} />
					</group>
					<group name='Fish' rotation={[-Math.PI / 2, 0, 0]} scale={100}>
						<skinnedMesh
							name='Fish_1'
							geometry={nodes.Fish_1.geometry}
							material={materials.Fish_Secondary}
							skeleton={nodes.Fish_1.skeleton}
						/>
						<skinnedMesh
							name='Fish_2'
							geometry={nodes.Fish_2.geometry}
							material={materials.Fish_Main}
							skeleton={nodes.Fish_2.skeleton}
						/>
						<skinnedMesh
							name='Fish_3'
							geometry={nodes.Fish_3.geometry}
							material={materials.Fish_Flaps}
							skeleton={nodes.Fish_3.skeleton}
						/>
						<skinnedMesh
							name='Fish_4'
							geometry={nodes.Fish_4.geometry}
							material={materials.Mouth}
							skeleton={nodes.Fish_4.skeleton}
						/>
						<skinnedMesh
							name='Fish_5'
							geometry={nodes.Fish_5.geometry}
							material={materials.Eye_White}
							skeleton={nodes.Fish_5.skeleton}
						/>
						<skinnedMesh
							name='Fish_6'
							geometry={nodes.Fish_6.geometry}
							material={materials.Eye_Black}
							skeleton={nodes.Fish_6.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/characters/Fish.glb");
